import { Raleway } from "next/font/google";
import "./globals.css";
import Menu from "./componentes/menu";

const raleway = Raleway();

export const metadata = {
  title: "convert Now",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${raleway.className} antialiased`}
      >
        <Menu />
        {children}
      </body>
    </html>
  );
}
